// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY5e2aB-oV5F7fEhW0vd4dctdfQCsoVGY',
    appId: '1:431561893779:web:84d121497c2dd1680daa66',
    messagingSenderId: '431561893779',
    projectId: 'halalapp2026',
    authDomain: 'halalapp2026.firebaseapp.com',
    storageBucket: 'halalapp2026.firebasestorage.app',
    measurementId: 'G-0DK4W9GG48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-W035d7-RQvgvLz_PIb1L8DAsXeQblAA',
    appId: '1:431561893779:android:5947e0cf728a1d4e0daa66',
    messagingSenderId: '431561893779',
    projectId: 'halalapp2026',
    storageBucket: 'halalapp2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN8owYl8Bygd6eB2H5LF2qHATnqJsHFC4',
    appId: '1:431561893779:ios:827485ae2a71652f0daa66',
    messagingSenderId: '431561893779',
    projectId: 'halalapp2026',
    storageBucket: 'halalapp2026.firebasestorage.app',
    iosBundleId: 'com.example.halalfoodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN8owYl8Bygd6eB2H5LF2qHATnqJsHFC4',
    appId: '1:431561893779:ios:827485ae2a71652f0daa66',
    messagingSenderId: '431561893779',
    projectId: 'halalapp2026',
    storageBucket: 'halalapp2026.firebasestorage.app',
    iosBundleId: 'com.example.halalfoodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY5e2aB-oV5F7fEhW0vd4dctdfQCsoVGY',
    appId: '1:431561893779:web:7d03e7348f227d510daa66',
    messagingSenderId: '431561893779',
    projectId: 'halalapp2026',
    authDomain: 'halalapp2026.firebaseapp.com',
    storageBucket: 'halalapp2026.firebasestorage.app',
    measurementId: 'G-WEPCX57EM8',
  );
}
